name: Generate Online Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Script
        run: |
          python3 Script/generate.py
    
      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Actions [Bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Repo.json
          git commit -m "Update Repo [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
